# Generated by Django 4.2.29 on 2026-03-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTypeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('informational', 'informational'), ('real_world', 'real_world'), ('cause_and_effect', 'cause_and_effect'), ('goal_based', 'goal_based')], max_length=32)),
                ('weight', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'answer_type_weights',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=64)),
                ('branch', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=128)),
                ('llm_version', models.CharField(blank=True, default='', max_length=64)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'knowledge_base_entries',
            },
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('preference_text', models.TextField()),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='goal_submitted', max_length=64)),
                ('conversation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('pending_remediation', models.JSONField(blank=True, null=True)),
                ('example_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_goals',
            },
        ),
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('domain', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('student_text', models.TextField(blank=True, default='')),
                ('evaluation_report', models.TextField(blank=True, default='')),
                ('structured_report', models.JSONField(blank=True, default=dict)),
                ('priority', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'self_assessments',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=100)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_badges',
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_goals',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('answer_style', models.CharField(default='informational', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_histories',
            },
        ),
        migrations.CreateModel(
            name='UserHobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_hobbies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('academic_level', models.CharField(blank=True, default='', max_length=50)),
                ('preferred_subject', models.CharField(blank=True, default='', max_length=50)),
                ('learning_style', models.CharField(blank=True, default='default', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('timezone', models.CharField(blank=True, default='', max_length=50)),
                ('cultural_background', models.CharField(blank=True, default='', max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('preferences_completed', models.BooleanField(default=False)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak', models.IntegerField(default=0)),
                ('weight_adjustment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserConversationState',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='conversation_state', serialize=False, to='main.userprofile')),
                ('conversation_id', models.CharField(blank=True, max_length=128, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('learning_summary', models.TextField(blank=True, default='')),
                ('item_count', models.IntegerField(default=0)),
                ('compacted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_conversation_state',
            },
        ),
        migrations.CreateModel(
            name='UserWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weakness', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='main.userprofile')),
            ],
            options={
                'db_table': 'user_weaknesses',
            },
        ),
        migrations.CreateModel(
            name='UserStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='main.userprofile')),
            ],
            options={
                'db_table': 'user_strengths',
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_admin'], name='idx_users_is_admin'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['preferences_completed'], name='idx_users_pref_done'),
        ),
        migrations.AddField(
            model_name='userhobby',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='learning_goal',
            field=models.ForeignKey(blank=True, db_column='learning_goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='main.learninggoal'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='learning_goal',
            field=models.ForeignKey(blank=True, db_column='learning_goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_assessments', to='main.learninggoal'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='main.userprofile'),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['domain', 'branch'], name='idx_kb_domain_branch'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebaseentry',
            constraint=models.UniqueConstraint(fields=('domain', 'branch'), name='uix_kb_domain_branch'),
        ),
        migrations.AddField(
            model_name='answertypeweight',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='answer_type_weights', to='main.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='userweakness',
            constraint=models.UniqueConstraint(fields=('user', 'weakness'), name='unique_user_weakness'),
        ),
        migrations.AddConstraint(
            model_name='userstrength',
            constraint=models.UniqueConstraint(fields=('user', 'strength'), name='unique_user_strength'),
        ),
        migrations.AddConstraint(
            model_name='userhobby',
            constraint=models.UniqueConstraint(fields=('user', 'hobby'), name='unique_user_hobby'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['timestamp'], name='idx_user_histories_timestamp'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['answer_style'], name='idx_hist_ans_style'),
        ),
        migrations.AddConstraint(
            model_name='usergoal',
            constraint=models.UniqueConstraint(fields=('user', 'goal'), name='unique_user_goal'),
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='unique_user_badge'),
        ),
        migrations.AddIndex(
            model_name='selfassessment',
            index=models.Index(fields=['username', 'created_at'], name='idx_sa_user_created'),
        ),
        migrations.AddIndex(
            model_name='selfassessment',
            index=models.Index(fields=['learning_goal', 'created_at'], name='idx_sa_goal_created'),
        ),
        migrations.AddIndex(
            model_name='learninggoal',
            index=models.Index(fields=['status'], name='idx_learning_goals_status'),
        ),
        migrations.AddConstraint(
            model_name='answertypeweight',
            constraint=models.UniqueConstraint(fields=('user', 'answer_type'), name='unique_user_answer_type'),
        ),
    ]
