# Generated by Django 4.2.29 on 2026-03-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cleanup_legacy_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='learning_style',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_subject',
        ),
    ]
