# Generated by Django 4.2.29 on 2026-04-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_learning_style_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
