# Generated by Django 4.2.29 on 2026-04-17

from django.db import migrations, models
import django.db.models.deletion


CREATE_CONCEPT_MAP_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS learning_goal_concept_maps (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    learning_goal_id BIGINT NOT NULL UNIQUE,
    status VARCHAR(32) DEFAULT 'pending',
    llm_version VARCHAR(64) DEFAULT '',
    summary LONGTEXT,
    content JSON,
    trace JSON,
    error_code VARCHAR(64) DEFAULT '',
    error_message LONGTEXT,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT learning_goal_concept_maps_goal_fk
        FOREIGN KEY (learning_goal_id) REFERENCES learning_goals(id) ON DELETE CASCADE,
    INDEX idx_goal_cmap_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

CREATE_CONCEPT_MAP_TABLE_SQLITE = """
CREATE TABLE IF NOT EXISTS learning_goal_concept_maps (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    learning_goal_id BIGINT NOT NULL UNIQUE REFERENCES learning_goals(id) DEFERRABLE INITIALLY DEFERRED,
    status VARCHAR(32) DEFAULT 'pending',
    llm_version VARCHAR(64) DEFAULT '',
    summary TEXT DEFAULT '',
    content TEXT DEFAULT '{}',
    trace TEXT DEFAULT '{}',
    error_code VARCHAR(64) DEFAULT '',
    error_message TEXT DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);
"""


def create_concept_map_table(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(CREATE_CONCEPT_MAP_TABLE_SQLITE)
        schema_editor.execute(
            "CREATE INDEX IF NOT EXISTS idx_goal_cmap_status ON learning_goal_concept_maps(status);"
        )
        return
    schema_editor.execute(CREATE_CONCEPT_MAP_TABLE_SQL)


def drop_concept_map_table(apps, schema_editor):
    del apps
    schema_editor.execute("DROP TABLE IF EXISTS learning_goal_concept_maps")


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_userprofile_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_concept_map_table, reverse_code=drop_concept_map_table)
            ],
            state_operations=[
                migrations.CreateModel(
                    name="LearningGoalConceptMap",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("status", models.CharField(default="pending", max_length=32)),
                        ("llm_version", models.CharField(blank=True, default="", max_length=64)),
                        ("summary", models.TextField(blank=True, default="")),
                        ("content", models.JSONField(blank=True, default=dict)),
                        ("trace", models.JSONField(blank=True, default=dict)),
                        ("error_code", models.CharField(blank=True, default="", max_length=64)),
                        ("error_message", models.TextField(blank=True, default="")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "learning_goal",
                            models.OneToOneField(
                                db_column="learning_goal_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="concept_map_asset",
                                to="main.learninggoal",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learning_goal_concept_maps",
                        "indexes": [models.Index(fields=["status"], name="idx_goal_cmap_status")],
                    },
                )
            ],
        )
    ]
