# Generated by Django 4.2.29 on 2026-04-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_concurrency_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='vector_store_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='vector_store_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='vector_store_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='UploadedLearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=16)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('openai_file_id', models.CharField(blank=True, default='', max_length=128)),
                ('vector_store_id', models.CharField(blank=True, default='', max_length=128)),
                ('vector_store_batch_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='uploaded', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_learning_materials', to='main.userprofile')),
            ],
            options={
                'db_table': 'uploaded_learning_materials',
                'indexes': [models.Index(fields=['learning_goal', 'status'], name='idx_ulm_goal_status'), models.Index(fields=['user', 'created_at'], name='idx_ulm_user_created')],
            },
        ),
    ]
