# Generated by Django 5.1.7 on 2026-05-10 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_chat_concept_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconceptsignal',
            name='source',
            field=models.CharField(choices=[('concept_map', 'concept_map'), ('rule', 'rule'), ('vector_match', 'vector_match'), ('vector_new', 'vector_new'), ('llm', 'llm'), ('fallback', 'fallback')], default='fallback', max_length=32),
        ),
        migrations.CreateModel(
            name='ConceptRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_key', models.CharField(max_length=160)),
                ('concept_label', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('baseline', 'baseline'), ('concept_map', 'concept_map'), ('mastery_state', 'mastery_state'), ('chat', 'chat'), ('probe', 'probe'), ('manual', 'manual')], default='chat', max_length=32)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='concept_registry_entries', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='concept_registry_entries', to='main.userprofile')),
            ],
            options={
                'db_table': 'concept_registry_entries',
                'indexes': [models.Index(fields=['user', 'learning_goal', 'updated_at'], name='idx_cre_user_goal_time'), models.Index(fields=['learning_goal', 'concept_key'], name='idx_cre_goal_concept')],
                'constraints': [models.UniqueConstraint(fields=('user', 'learning_goal', 'concept_key'), name='uix_cre_user_goal_concept')],
            },
        ),
    ]
