# Generated by Codex on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_concept_registry_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnermasterystate",
            name="curve_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="learnermasterystate",
            name="curve_evidence_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="learnermasterystate",
            name="curve_reason",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="learnermasterystate",
            name="dimension_curve_confidences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="learnermasterystate",
            name="dimension_curve_patterns",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
