# Generated by Django 5.2.3 on 2026-06-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_curve_pattern_v2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cultural_background',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight_adjustment_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='xp',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
        migrations.DeleteModel(
            name='UserConversationState',
        ),
        migrations.DeleteModel(
            name='UserGoal',
        ),
        migrations.DeleteModel(
            name='UserHobby',
        ),
        migrations.DeleteModel(
            name='UserStrength',
        ),
        migrations.DeleteModel(
            name='UserWeakness',
        ),
    ]
