# Generated by Django 4.2.29 on 2026-07-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerBehaviorEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_key', models.CharField(blank=True, default='', max_length=160)),
                ('event_type', models.CharField(choices=[('preference_state_updated', 'preference_state_updated'), ('knowledge_map_snapshot', 'knowledge_map_snapshot'), ('understanding_signal', 'understanding_signal'), ('explicit_preference', 'explicit_preference')], max_length=48)),
                ('source', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=160)),
                ('trace_id', models.CharField(blank=True, default='', max_length=128)),
                ('schema_version', models.CharField(default='learner_behavior_v1', max_length=40)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('learning_goal', models.ForeignKey(blank=True, db_column='learning_goal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='behavior_evidence', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='behavior_evidence', to='main.userprofile')),
            ],
            options={
                'db_table': 'learner_behavior_evidence',
            },
        ),
        migrations.CreateModel(
            name='LearnerPreferenceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicit_preferences', models.JSONField(blank=True, default=dict)),
                ('inferred_preferences', models.JSONField(blank=True, default=dict)),
                ('delivery_preferences', models.JSONField(blank=True, default=dict)),
                ('confidence_by_signal', models.JSONField(blank=True, default=dict)),
                ('style_feedback_count', models.PositiveIntegerField(default=0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('schema_version', models.CharField(default='learner_preference_v1', max_length=40)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_evidence', models.ForeignKey(blank=True, db_column='last_evidence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.learnerbehaviorevidence')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='learner_preference_state', to='main.userprofile')),
            ],
            options={
                'db_table': 'learner_preference_states',
                'indexes': [models.Index(fields=['updated_at'], name='idx_lps_updated')],
            },
        ),
        migrations.CreateModel(
            name='LearnerMisconceptionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_key', models.CharField(max_length=160)),
                ('misconception_key', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'active'), ('resolved', 'resolved')], default='active', max_length=24)),
                ('confidence', models.FloatField(default=0.0)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('source_summary', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.CharField(default='learner_misconception_v1', max_length=40)),
                ('policy_version', models.CharField(default='misconception_policy_v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_evidence', models.ForeignKey(blank=True, db_column='first_evidence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_misconception_observations', to='main.adaptiveinteractionevent')),
                ('last_evidence', models.ForeignKey(blank=True, db_column='last_evidence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_misconception_observations', to='main.adaptiveinteractionevent')),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='misconception_states', to='main.learninggoal')),
                ('resolved_by_evidence', models.ForeignKey(blank=True, db_column='resolved_by_evidence_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_misconceptions', to='main.adaptiveinteractionevent')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='misconception_states', to='main.userprofile')),
            ],
            options={
                'db_table': 'learner_misconception_states',
                'indexes': [models.Index(fields=['user', 'learning_goal', 'status'], name='idx_lmc_user_goal_status'), models.Index(fields=['learning_goal', 'concept_key', 'status'], name='idx_lmc_goal_concept_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='learnermisconceptionstate',
            constraint=models.UniqueConstraint(fields=('user', 'learning_goal', 'concept_key', 'misconception_key'), name='uix_lmc_user_goal_concept_mis'),
        ),
        migrations.AddIndex(
            model_name='learnerbehaviorevidence',
            index=models.Index(fields=['user', 'occurred_at'], name='idx_lbe_user_time'),
        ),
        migrations.AddIndex(
            model_name='learnerbehaviorevidence',
            index=models.Index(fields=['learning_goal', 'event_type', 'occurred_at'], name='idx_lbe_goal_type_time'),
        ),
        migrations.AddIndex(
            model_name='learnerbehaviorevidence',
            index=models.Index(fields=['idempotency_key'], name='idx_lbe_idempotency'),
        ),
    ]
