# Generated by Django 4.2.29 on 2026-07-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_p2_4_learner_episodic_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('run_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=96)),
                ('request_sha256', models.CharField(max_length=64)),
                ('plan_sha256', models.CharField(max_length=64)),
                ('authority_scope', models.CharField(choices=[('read', 'read'), ('propose', 'propose'), ('request', 'request'), ('mixed', 'mixed')], max_length=24)),
                ('status', models.CharField(choices=[('running', 'running'), ('accepted', 'accepted'), ('blocked', 'blocked'), ('abstained', 'abstained'), ('failed', 'failed')], default='running', max_length=24)),
                ('reason_code', models.CharField(blank=True, default='', max_length=96)),
                ('step_budget', models.PositiveSmallIntegerField(default=0)),
                ('token_budget', models.PositiveIntegerField(default=0)),
                ('tool_budget', models.PositiveSmallIntegerField(default=0)),
                ('model_label', models.CharField(blank=True, default='', max_length=96)),
                ('prompt_sha256', models.CharField(max_length=64)),
                ('trace_id', models.CharField(blank=True, default='', max_length=128)),
                ('mastery_write_authorized', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, db_column='conversation_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='main.learningconversation')),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='main.userprofile')),
            ],
            options={
                'db_table': 'agent_runs',
            },
        ),
        migrations.CreateModel(
            name='AgentToolInvocation',
            fields=[
                ('invocation_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=96)),
                ('request_sha256', models.CharField(max_length=64)),
                ('args_sha256', models.CharField(max_length=64)),
                ('result_sha256', models.CharField(max_length=64)),
                ('plan_sha256', models.CharField(max_length=64)),
                ('tool_name', models.CharField(max_length=64)),
                ('tool_version', models.CharField(max_length=48)),
                ('authority', models.CharField(choices=[('read', 'read'), ('propose', 'propose'), ('request', 'request')], max_length=24)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('blocked', 'blocked'), ('abstained', 'abstained'), ('failed', 'failed')], max_length=24)),
                ('reason_code', models.CharField(max_length=96)),
                ('step_index', models.PositiveSmallIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('budget_remaining', models.PositiveSmallIntegerField(default=0)),
                ('model_label', models.CharField(blank=True, default='', max_length=96)),
                ('prompt_sha256', models.CharField(max_length=64)),
                ('trace_id', models.CharField(blank=True, default='', max_length=128)),
                ('resource_ref', models.CharField(blank=True, default='', max_length=64)),
                ('mastery_write_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, db_column='conversation_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tool_invocations', to='main.learningconversation')),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_invocations', to='main.learninggoal')),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='main.agentrun')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_invocations', to='main.userprofile')),
            ],
            options={
                'db_table': 'agent_tool_invocations',
                'indexes': [models.Index(fields=['run', 'step_index'], name='idx_ati_run_step'), models.Index(fields=['user', 'learning_goal', 'created_at'], name='idx_ati_scope_time'), models.Index(fields=['tool_name', 'status', 'created_at'], name='idx_ati_tool_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='agenttoolinvocation',
            constraint=models.UniqueConstraint(fields=('run', 'tool_name', 'idempotency_key'), name='uix_ati_run_tool_idem'),
        ),
        migrations.AddConstraint(
            model_name='agenttoolinvocation',
            constraint=models.CheckConstraint(check=models.Q(('mastery_write_authorized', False)), name='chk_ati_no_mastery'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['user', 'learning_goal', 'started_at'], name='idx_arun_scope_time'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', 'started_at'], name='idx_arun_status_time'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(fields=('user', 'learning_goal', 'idempotency_key'), name='uix_arun_scope_idem'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.CheckConstraint(check=models.Q(('mastery_write_authorized', False)), name='chk_arun_no_mastery'),
        ),
    ]
