# Generated by Django 4.2.29 on 2026-07-21 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_p3_agent_tool_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentShadowRun',
            fields=[
                ('shadow_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=96)),
                ('request_sha256', models.CharField(max_length=64)),
                ('local_plan_sha256', models.CharField(max_length=64)),
                ('shadow_plan_sha256', models.CharField(max_length=64)),
                ('prompt_sha256', models.CharField(max_length=64)),
                ('model_label', models.CharField(default='gpt-5.6-luna', max_length=96)),
                ('model_sha256', models.CharField(max_length=64)),
                ('available_tools_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('failed', 'failed'), ('fenced', 'fenced')], default='running', max_length=24)),
                ('outcome', models.CharField(choices=[('pending', 'pending'), ('matched', 'matched'), ('diverged', 'diverged'), ('provider_failure', 'provider_failure'), ('fenced', 'fenced')], default='pending', max_length=32)),
                ('provider_status', models.CharField(choices=[('not_called', 'not_called'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='not_called', max_length=24)),
                ('local_intent', models.CharField(choices=[('tutor', 'tutor'), ('retrieval', 'retrieval'), ('weakness', 'weakness'), ('probe', 'probe'), ('memory_preference', 'memory_preference'), ('ambiguous', 'ambiguous'), ('no_evidence', 'no_evidence'), ('safety_block', 'safety_block'), ('unavailable', 'unavailable')], max_length=32)),
                ('shadow_intent', models.CharField(choices=[('tutor', 'tutor'), ('retrieval', 'retrieval'), ('weakness', 'weakness'), ('probe', 'probe'), ('memory_preference', 'memory_preference'), ('ambiguous', 'ambiguous'), ('no_evidence', 'no_evidence'), ('safety_block', 'safety_block'), ('unavailable', 'unavailable')], default='unavailable', max_length=32)),
                ('local_teaching_mode', models.CharField(choices=[('default', 'default'), ('concise', 'concise'), ('worked_example', 'worked_example'), ('socratic', 'socratic'), ('review', 'review'), ('unavailable', 'unavailable')], max_length=32)),
                ('shadow_teaching_mode', models.CharField(choices=[('default', 'default'), ('concise', 'concise'), ('worked_example', 'worked_example'), ('socratic', 'socratic'), ('review', 'review'), ('unavailable', 'unavailable')], default='unavailable', max_length=32)),
                ('local_tool_count', models.PositiveSmallIntegerField(default=0)),
                ('shadow_tool_count', models.PositiveSmallIntegerField(default=0)),
                ('decision_match', models.BooleanField(default=False)),
                ('tool_set_match', models.BooleanField(default=False)),
                ('provider_call_count', models.PositiveSmallIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('mastery_write_authorized', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, db_column='conversation_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_shadow_runs', to='main.learningconversation')),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_shadow_runs', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='agent_shadow_runs', to='main.userprofile')),
            ],
            options={
                'db_table': 'agent_shadow_runs',
                'indexes': [models.Index(fields=['user', 'learning_goal', 'started_at'], name='idx_ashadow_scope_time'), models.Index(fields=['status', 'outcome', 'started_at'], name='idx_ashadow_result_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='agentshadowrun',
            constraint=models.UniqueConstraint(fields=('user', 'learning_goal', 'idempotency_key'), name='uix_ashadow_scope_idem'),
        ),
        migrations.AddConstraint(
            model_name='agentshadowrun',
            constraint=models.CheckConstraint(check=models.Q(('mastery_write_authorized', False)), name='chk_ashadow_no_mastery'),
        ),
        migrations.AddConstraint(
            model_name='agentshadowrun',
            constraint=models.CheckConstraint(check=models.Q(('provider_call_count__lte', 1)), name='chk_ashadow_one_call'),
        ),
        migrations.AddConstraint(
            model_name='agentshadowrun',
            constraint=models.CheckConstraint(check=models.Q(('total_tokens__gte', models.F('input_tokens') + models.F('output_tokens'))), name='chk_ashadow_token_sum'),
        ),
    ]
