# Generated by Django 4.2.29 on 2026-07-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_p4_agent_shadow_runs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalActionApproval',
            fields=[
                ('approval_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=96)),
                ('action_type', models.CharField(choices=[('calendar.create_study_session', 'calendar.create_study_session')], max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'proposed'), ('approved', 'approved'), ('rejected', 'rejected'), ('expired', 'expired'), ('consumed', 'consumed'), ('revoked', 'revoked')], default='proposed', max_length=24)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('preview_sha256', models.CharField(max_length=64)),
                ('request_sha256', models.CharField(max_length=64)),
                ('grant_generation', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_write_authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, db_column='conversation_key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_action_approvals', to='main.learningconversation')),
            ],
            options={
                'db_table': 'external_action_approvals',
            },
        ),
        migrations.CreateModel(
            name='ExternalConnectorGrant',
            fields=[
                ('grant_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('sandbox', 'sandbox')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'active'), ('revoked', 'revoked'), ('expired', 'expired')], default='active', max_length=24)),
                ('capabilities', models.JSONField(default=list)),
                ('generation', models.PositiveIntegerField(default=1)),
                ('configuration_sha256', models.CharField(max_length=64)),
                ('consent_version', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_connector_grants', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_connector_grants', to='main.userprofile')),
            ],
            options={
                'db_table': 'external_connector_grants',
            },
        ),
        migrations.CreateModel(
            name='ExternalActionExecution',
            fields=[
                ('execution_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=96)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('result_sha256', models.CharField(max_length=64)),
                ('external_ref_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('fenced', 'fenced')], default='running', max_length=24)),
                ('reason_code', models.CharField(max_length=96)),
                ('connector_call_count', models.PositiveSmallIntegerField(default=0)),
                ('mastery_write_authorized', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval', models.OneToOneField(db_column='approval_id', on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='main.externalactionapproval')),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_action_executions', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_action_executions', to='main.userprofile')),
            ],
            options={
                'db_table': 'external_action_executions',
            },
        ),
        migrations.AddField(
            model_name='externalactionapproval',
            name='grant',
            field=models.ForeignKey(db_column='grant_id', on_delete=django.db.models.deletion.CASCADE, related_name='action_approvals', to='main.externalconnectorgrant'),
        ),
        migrations.AddField(
            model_name='externalactionapproval',
            name='learning_goal',
            field=models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_action_approvals', to='main.learninggoal'),
        ),
        migrations.AddField(
            model_name='externalactionapproval',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_action_approvals', to='main.userprofile'),
        ),
        migrations.AddIndex(
            model_name='externalconnectorgrant',
            index=models.Index(fields=['user', 'learning_goal', 'provider', 'status'], name='idx_xgrant_scope_status'),
        ),
        migrations.AddIndex(
            model_name='externalconnectorgrant',
            index=models.Index(fields=['status', 'expires_at'], name='idx_xgrant_status_expiry'),
        ),
        migrations.AddConstraint(
            model_name='externalconnectorgrant',
            constraint=models.UniqueConstraint(fields=('user', 'learning_goal', 'provider', 'generation'), name='uix_xgrant_scope_generation'),
        ),
        migrations.AddIndex(
            model_name='externalactionexecution',
            index=models.Index(fields=['user', 'learning_goal', 'status', 'started_at'], name='idx_xexecution_scope_status'),
        ),
        migrations.AddConstraint(
            model_name='externalactionexecution',
            constraint=models.UniqueConstraint(fields=('user', 'learning_goal', 'idempotency_key'), name='uix_xexecution_scope_idem'),
        ),
        migrations.AddConstraint(
            model_name='externalactionexecution',
            constraint=models.CheckConstraint(check=models.Q(('connector_call_count__lte', 1)), name='chk_xexecution_one_call'),
        ),
        migrations.AddConstraint(
            model_name='externalactionexecution',
            constraint=models.CheckConstraint(check=models.Q(('mastery_write_authorized', False)), name='chk_xexecution_no_mastery'),
        ),
        migrations.AddIndex(
            model_name='externalactionapproval',
            index=models.Index(fields=['user', 'learning_goal', 'status', 'created_at'], name='idx_xapproval_scope_status'),
        ),
        migrations.AddIndex(
            model_name='externalactionapproval',
            index=models.Index(fields=['status', 'expires_at'], name='idx_xapproval_status_expiry'),
        ),
        migrations.AddConstraint(
            model_name='externalactionapproval',
            constraint=models.UniqueConstraint(fields=('user', 'learning_goal', 'idempotency_key'), name='uix_xapproval_scope_idem'),
        ),
        migrations.AddConstraint(
            model_name='externalactionapproval',
            constraint=models.CheckConstraint(check=models.Q(('mastery_write_authorized', False)), name='chk_xapproval_no_mastery'),
        ),
    ]
