# Generated by Django 4.2.29 on 2026-07-23 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_repository_architecture_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninggoal',
            name='conversation_id',
        ),
        migrations.DeleteModel(
            name='LearnerPreferenceState',
        ),
    ]
