# Generated by Django 4.2.29 on 2026-07-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_learninggoal_conversation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningconversation',
            name='retention_class',
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='assessment_snapshot',
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='priority',
        ),
    ]
