# Generated by Django 4.2.29 on 2026-07-23 03:27

from django.db import migrations, models
import django.db.models.deletion


def remove_unscoped_history(apps, schema_editor):
    UserHistory = apps.get_model("main", "UserHistory")
    UserHistory.objects.filter(
        models.Q(learning_goal__isnull=True)
        | models.Q(conversation__isnull=True)
        | models.Q(event_key__isnull=True)
        | models.Q(event_key="")
        | models.Q(scope_status="legacy_unscoped")
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_redundant_persistence_fields'),
    ]

    operations = [
        migrations.RunPython(remove_unscoped_history, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userhistory',
            name='conversation',
            field=models.ForeignKey(db_column='conversation_key', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='main.learningconversation'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='event_key',
            field=models.CharField(max_length=96, unique=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='learning_goal',
            field=models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='main.learninggoal'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='scope_status',
            field=models.CharField(choices=[('active', 'active'), ('tombstoned', 'tombstoned')], default='active', max_length=24),
        ),
    ]
