# Generated by Django 4.2.29 on 2026-07-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_self_assessment_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSAReferenceBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('frozen', 'frozen')], default='frozen', editable=False, max_length=24)),
                ('framework_version', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=64)),
                ('taxonomy_sha256', models.CharField(max_length=64)),
                ('generation_input_sha256', models.CharField(max_length=64, unique=True)),
                ('blueprint_sha256', models.CharField(db_index=True, max_length=64)),
                ('goal_snapshot', models.JSONField(default=dict)),
                ('learner_context_snapshot', models.JSONField(default=dict)),
                ('core_concepts_snapshot', models.JSONField(default=list)),
                ('blueprint', models.JSONField(default=dict)),
                ('model', models.CharField(max_length=96)),
                ('model_configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_goal', models.ForeignKey(db_column='learning_goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='csa_reference_blueprints', to='main.learninggoal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='csa_reference_blueprints', to='main.userprofile')),
            ],
            options={
                'db_table': 'csa_reference_blueprints',
            },
        ),
        migrations.CreateModel(
            name='CSAReferenceBlueprintEvidenceRetrieval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('Facts', 'Facts'), ('Strategies', 'Strategies'), ('Procedures', 'Procedures'), ('Rationales', 'Rationales')], max_length=24)),
                ('blueprint', models.ForeignKey(db_column='blueprint_id', on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_links', to='main.csareferenceblueprint')),
                ('retrieval_decision', models.ForeignKey(db_column='retrieval_decision_id', on_delete=django.db.models.deletion.PROTECT, related_name='csa_blueprint_links', to='main.retrievaldecision')),
            ],
            options={
                'db_table': 'csa_reference_blueprint_retrievals',
            },
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='reference_blueprint',
            field=models.ForeignKey(blank=True, db_column='reference_blueprint_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_assessments', to='main.csareferenceblueprint'),
        ),
        migrations.AddConstraint(
            model_name='csareferenceblueprintevidenceretrieval',
            constraint=models.UniqueConstraint(fields=('blueprint', 'dimension'), name='uix_csarbr_blueprint_dimension'),
        ),
        migrations.AddConstraint(
            model_name='csareferenceblueprintevidenceretrieval',
            constraint=models.UniqueConstraint(fields=('blueprint', 'retrieval_decision'), name='uix_csarbr_blueprint_retrieval'),
        ),
        migrations.AddIndex(
            model_name='csareferenceblueprint',
            index=models.Index(fields=['user', 'learning_goal', 'created_at'], name='idx_csarb_scope_created'),
        ),
        migrations.AddIndex(
            model_name='csareferenceblueprint',
            index=models.Index(fields=['taxonomy_sha256'], name='idx_csarb_taxonomy'),
        ),
    ]
