# Generated by Django 4.2.29 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0037_csa_reference_blueprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="csareferenceblueprint",
            name="scope_contract",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="csareferenceblueprint",
            name="target_problem_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="selfassessment",
            name="scope_contract",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="selfassessment",
            name="target_problem",
            field=models.TextField(blank=True, default=""),
        ),
    ]
