# Generated by Django 4.2.29 on 2026-07-23 02:01

import learning_apps.application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adaptive_agent', '0012_alter_agentrunevent_event_type'),
        ('main', '0032_repository_architecture_cleanup'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='ExecutionRun',
            fields=[
                ('execution_id', models.CharField(default=learning_apps.application.models.generate_execution_id, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('entrypoint', models.CharField(max_length=24)),
                ('workflow', models.CharField(max_length=96)),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='running', max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='adaptive_agent.learningagentrun')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capability_executions', to='main.learningconversation')),
                ('learning_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_executions', to='main.learninggoal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_executions', to='main.userprofile')),
            ],
            options={
                'db_table': 'capability_execution_runs_v2',
            },
        ),
        migrations.CreateModel(
            name='CapabilityInvocation',
            fields=[
                ('invocation_id', models.CharField(default=learning_apps.application.models.generate_invocation_id, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('capability_name', models.CharField(max_length=96)),
                ('capability_version', models.CharField(max_length=32)),
                ('authority', models.CharField(max_length=24)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('blocked', 'blocked'), ('failed', 'failed')], max_length=24)),
                ('idempotency_key', models.CharField(max_length=96)),
                ('input_sha256', models.CharField(max_length=64)),
                ('output_sha256', models.CharField(max_length=64)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mastery_write_authorized', models.BooleanField(default=False, editable=False)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invocations', to='application.executionrun')),
            ],
            options={
                'db_table': 'capability_invocations_v2',
            },
        ),
        migrations.CreateModel(
            name='LearningActionProposal',
            fields=[
                ('proposal_id', models.CharField(default=learning_apps.application.models.generate_proposal_id, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('proposal_type', models.CharField(choices=[('quiz', 'quiz'), ('probe', 'probe'), ('review_plan', 'review_plan'), ('external_study_session', 'external_study_session')], max_length=40)),
                ('status', models.CharField(choices=[('approved_draft', 'approved_draft'), ('activated', 'activated'), ('cancelled', 'cancelled'), ('expired', 'expired')], default='approved_draft', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=96, unique=True)),
                ('approved_at', models.DateTimeField()),
                ('external_action_executed', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_proposals', to='adaptive_agent.learningagentrun')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_action_proposals', to='main.learningconversation')),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_action_proposals', to='main.learninggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_action_proposals', to='main.userprofile')),
            ],
            options={
                'db_table': 'learning_action_proposals_v2',
                'indexes': [models.Index(fields=['user', 'learning_goal', 'status', 'created_at'], name='idx_lap_scope_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='learningactionproposal',
            constraint=models.CheckConstraint(check=models.Q(('external_action_executed', False)), name='chk_lap_no_external_execute'),
        ),
        migrations.AddIndex(
            model_name='executionrun',
            index=models.Index(fields=['user', 'learning_goal', 'started_at'], name='idx_cap_exec_scope'),
        ),
        migrations.AddIndex(
            model_name='capabilityinvocation',
            index=models.Index(fields=['capability_name', 'status', 'created_at'], name='idx_cap_inv_status'),
        ),
        migrations.AddConstraint(
            model_name='capabilityinvocation',
            constraint=models.UniqueConstraint(fields=('capability_name', 'idempotency_key'), name='uix_cap_invocation_idem'),
        ),
        migrations.AddConstraint(
            model_name='capabilityinvocation',
            constraint=models.CheckConstraint(check=models.Q(('mastery_write_authorized', False)), name='chk_cap_inv_no_mastery'),
        ),
            ],
        ),
    ]
