# Generated by Django 5.2.3 on 2026-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassroom',
            name='term',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
