# Generated by Django 4.2.29 on 2026-07-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_agent', '0004_alter_learningagentrun_max_turns'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capabilityinvocation',
            name='uix_cap_invocation_idem',
        ),
        migrations.AddField(
            model_name='capabilityinvocation',
            name='output_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='capabilityinvocation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('blocked', 'blocked'), ('failed', 'failed')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='capabilityinvocation',
            constraint=models.UniqueConstraint(fields=('capability_name', 'idempotency_key'), name='uix_cap_invocation_idem'),
        ),
    ]
