# Generated by Django 4.2.29 on 2026-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_agent', '0005_remove_capabilityinvocation_uix_cap_invocation_idem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningagentrun',
            name='elapsed_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningagentrun',
            name='input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningagentrun',
            name='model_request_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningagentrun',
            name='output_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
