# Generated by Django 4.2.29 on 2026-07-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_agent', '0006_learningagentrun_elapsed_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityinvocation',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='capabilityinvocation',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
