# Generated by Django 4.2.29 on 2026-07-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_p5_external_capability_control'),
        ('adaptive_agent', '0007_capabilityinvocation_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionrun',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capability_executions', to='main.learningconversation'),
        ),
        migrations.AlterField(
            model_name='executionrun',
            name='learning_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_executions', to='main.learninggoal'),
        ),
        migrations.AlterField(
            model_name='executionrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capability_executions', to='main.userprofile'),
        ),
    ]
