# Generated by Django 4.2.29 on 2026-07-21 13:09

import learning_apps.adaptive_agent.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_p5_external_capability_control'),
        ('adaptive_agent', '0008_alter_executionrun_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActionProposal',
            fields=[
                ('proposal_id', models.CharField(default=learning_apps.adaptive_agent.models.generate_proposal_id, editable=False, max_length=48, primary_key=True, serialize=False)),
                ('proposal_type', models.CharField(choices=[('quiz', 'quiz'), ('probe', 'probe'), ('review_plan', 'review_plan'), ('external_study_session', 'external_study_session')], max_length=40)),
                ('status', models.CharField(choices=[('approved_draft', 'approved_draft'), ('activated', 'activated'), ('cancelled', 'cancelled'), ('expired', 'expired')], default='approved_draft', max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=96, unique=True)),
                ('approved_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('external_action_executed', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_proposals', to='adaptive_agent.learningagentrun')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_action_proposals', to='main.learningconversation')),
                ('learning_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_action_proposals', to='main.learninggoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_action_proposals', to='main.userprofile')),
            ],
            options={
                'db_table': 'learning_action_proposals_v2',
                'indexes': [models.Index(fields=['user', 'learning_goal', 'status', 'created_at'], name='idx_lap_scope_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='learningactionproposal',
            constraint=models.CheckConstraint(check=models.Q(('external_action_executed', False)), name='chk_lap_no_external_execute'),
        ),
    ]
