# Generated by Django 4.2.29 on 2026-07-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_p5_external_capability_control"),
        ("adaptive_agent", "0009_learningactionproposal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrunevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("run_started", "run_started"),
                    ("memory_loaded", "memory_loaded"),
                    ("plan_updated", "plan_updated"),
                    ("skill_selected", "skill_selected"),
                    ("tool_requested", "tool_requested"),
                    ("tool_started", "tool_started"),
                    ("tool_completed", "tool_completed"),
                    ("evidence_attached", "evidence_attached"),
                    ("clarification_requested", "clarification_requested"),
                    ("approval_requested", "approval_requested"),
                    ("approval_resolved", "approval_resolved"),
                    ("answer_streaming", "answer_streaming"),
                    ("run_completed", "run_completed"),
                    ("run_failed", "run_failed"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="learningagentrun",
            name="conversation_memory_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="AgentConversationMemory",
            fields=[
                (
                    "conversation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="agent_conversation_memory",
                        serialize=False,
                        to="main.learningconversation",
                    ),
                ),
                (
                    "conversation_generation",
                    models.PositiveIntegerField(),
                ),
                ("policy_version", models.CharField(max_length=64)),
                ("encrypted_state", models.TextField()),
                ("state_sha256", models.CharField(max_length=64)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                ("compacted_turn_count", models.PositiveIntegerField(default=0)),
                ("last_history_id", models.PositiveBigIntegerField(default=0)),
                ("mastery_write_authorized", models.BooleanField(default=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "learning_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversation_memories",
                        to="main.learninggoal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_conversation_memories",
                        to="main.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "agent_conversation_memories_v2",
                "indexes": [
                    models.Index(
                        fields=["user", "learning_goal", "updated_at"],
                        name="idx_av2_memory_scope",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="agentconversationmemory",
            constraint=models.UniqueConstraint(
                fields=("user", "learning_goal", "conversation_generation"),
                name="uix_av2_memory_scope_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentconversationmemory",
            constraint=models.CheckConstraint(
                check=models.Q(("mastery_write_authorized", False)),
                name="chk_av2_memory_no_mastery",
            ),
        ),
    ]
