# Generated by Django 4.2.29 on 2026-07-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_agent', '0012_alter_agentrunevent_event_type'),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningactionproposal',
            name='activated_at',
        ),
        migrations.DeleteModel(
            name='OutboxEvent',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.RemoveField(
            model_name='capabilityinvocation',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='executionrun',
            name='agent_run',
        ),
        migrations.RemoveField(
            model_name='executionrun',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='executionrun',
            name='learning_goal',
        ),
        migrations.RemoveField(
            model_name='executionrun',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learningactionproposal',
            name='agent_run',
        ),
        migrations.RemoveField(
            model_name='learningactionproposal',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='learningactionproposal',
            name='learning_goal',
        ),
        migrations.RemoveField(
            model_name='learningactionproposal',
            name='user',
        ),
        migrations.DeleteModel(
            name='CapabilityInvocation',
        ),
        migrations.DeleteModel(
            name='ExecutionRun',
        ),
        migrations.DeleteModel(
            name='LearningActionProposal',
        ),
            ],
        ),
    ]
